### ISSUE TITLE
Adding a new boilerplate

### ISSUE THREAD

**Issue by chrisfinazzo** [jcoulaud/Boilerplate-app#1]
So, I ran `node generator.js` inside of `/generator` and it imploded: 

<img width="585" alt="screen shot 2017-04-13 at 4 15 48 pm" src="https://cloud.githubusercontent.com/assets/1534882/25022666/c8793278-2064-11e7-9836-e1cf2481df65.png">

Can you clarify what you mean by the following?: 

> It will build and extends every languages which are in the language.js file to generate a unique .json file by language.
Do remove every language.json file before running this command!

Nuking the contents of `src/languages` probably isn't what you meant - I assume :-)

**Comment by jcoulaud** [comment]
Actually it seems that you didn't add your .env in the folder :)
As you can see in the generator.js, there are those lines :

```
// Init Github API
const github = new GithubApi({
  headers: {
    'user-agent': process.env.GITHUB_USER_AGENT,
  }
});
github.authenticate({
  type: 'token',
  token: process.env.GITHUB_TOKEN,
});
```

You have to put your credentials in order to make it works :)

**Comment by chrisfinazzo** [comment]
SyntaxError: Invalid or unexpected token MY_GITHUB_TOKEN
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)

These _should_ still be valid - maybe I need to generate...

**Comment by jcoulaud** [comment]
Do you have set your ENV variables in the .env file ?
```
GITHUB_TOKEN="****"
GITHUB_USER_AGENT="****"
```

> https://github.com/settings/tokens

**Comment by jcoulaud** [comment]
Hey @chrisfinazzo , did you succeed?

**Comment by jcoulaud** [comment]
No response. Closing this issue.
Come back at me if you have any question :)
