### ISSUE TITLE
Vue Examples

### ISSUE THREAD

**Issue by sdras** [jcoulaud/Boilerplate-app#3]
Hi! Thanks for making this great resource! I just wanted to let you know, if you're not aware of it already, that this list has tons of examples and some boilerplates if you're looking for a place to start: [https://github.com/vuejs/awesome-vue](https://github.com/vuejs/awesome-vue).

Let me know if you want any help getting some in, I'd be happy to contribute.

Thanks!

**Comment by jcoulaud** [comment]
Hey!
Thank you for this great resource!
I'm adding it to my bookmarks right now in order to take a look at it when I'll add Vue.js :)
Thank you again
